name: Yaeli-test
favicon: null
layout_spectrum: 0.5979863638058305
typography_spectrum: 0.6608755027409643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b3b5aa'
    - '#0c1013'
    - '#891427'
    - '#d06871'
  brandStrength: 0.7121456121094525
  lightness: 0.11910339281894267
  saturation: 0.4760582894086838
  rhythmicContrast: 0.1007034545764327
purpose: []
